namespace SkinRoyale
{
	public partial class frmMain : global::VisualPlus.Toolkit.Dialogs.VisualForm
	{
		protected override void Dispose(bool disposing)
		{
			bool flag = disposing && components != null;
			if (flag)
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		private void InitializeComponent()
		{
			components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager resources = new global::System.ComponentModel.ComponentResourceManager(typeof(global::SkinRoyale.frmMain));
			global::VisualPlus.Structure.TextStyle textStyle = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle2 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle3 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle4 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle5 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle6 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle7 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle8 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle9 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle10 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle11 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle12 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle13 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle14 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle15 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle16 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle17 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle18 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.TextStyle textStyle19 = new global::VisualPlus.Structure.TextStyle();
			global::VisualPlus.Structure.Border border = new global::VisualPlus.Structure.Border();
			btnStop = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton();
			visualLabel1 = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			cmbCapture = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox();
			btnStart = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton();
			btnCombo = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton();
			lblErrors = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			lblInvalid = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			lblValid = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			visualLabel5 = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			visualLabel4 = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			visualLabel3 = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			visualLabel2 = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			cmbProxyType = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox();
			btnProxy = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton();
			lblChecked = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			lblCheckedString = new global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel();
			base.SuspendLayout();
			_visualControlBox.HelpButton.BackColorState.Disabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.HelpButton.BackColorState.Enabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.HelpButton.BackColorState.Hover = global::System.Drawing.Color.FromArgb(190, 186, 186);
			_visualControlBox.HelpButton.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(105, 105, 105);
			_visualControlBox.HelpButton.BoxType = global::VisualPlus.Structure.ControlBoxButton.ControlBoxType.Default;
			_visualControlBox.HelpButton.ForeColorState.Disabled = global::System.Drawing.Color.FromArgb(105, 105, 105);
			_visualControlBox.HelpButton.ForeColorState.Enabled = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.HelpButton.ForeColorState.Hover = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.HelpButton.ForeColorState.Pressed = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.HelpButton.Image = (global::System.Drawing.Image)resources.GetObject("resource.Image");
			_visualControlBox.HelpButton.Location = new global::System.Drawing.Point(0, 0);
			_visualControlBox.HelpButton.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			_visualControlBox.HelpButton.Name = "";
			_visualControlBox.HelpButton.OffsetLocation = new global::System.Drawing.Point(0, 1);
			_visualControlBox.HelpButton.Size = new global::System.Drawing.Size(24, 25);
			_visualControlBox.HelpButton.TabIndex = 0;
			_visualControlBox.HelpButton.Text = "s";
			textStyle.Disabled = global::System.Drawing.Color.Empty;
			textStyle.Enabled = global::System.Drawing.Color.Empty;
			textStyle.Hover = global::System.Drawing.Color.Empty;
			textStyle.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			_visualControlBox.HelpButton.TextStyle = textStyle;
			_visualControlBox.HelpButton.Visible = false;
			_visualControlBox.Location = new global::System.Drawing.Point(639, 3);
			_visualControlBox.MaximizeButton.BackColorState.Disabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.MaximizeButton.BackColorState.Enabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.MaximizeButton.BackColorState.Hover = global::System.Drawing.Color.FromArgb(190, 186, 186);
			_visualControlBox.MaximizeButton.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(105, 105, 105);
			_visualControlBox.MaximizeButton.BoxType = global::VisualPlus.Structure.ControlBoxButton.ControlBoxType.Default;
			_visualControlBox.MaximizeButton.ForeColorState.Disabled = global::System.Drawing.Color.FromArgb(105, 105, 105);
			_visualControlBox.MaximizeButton.ForeColorState.Enabled = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MaximizeButton.ForeColorState.Hover = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MaximizeButton.ForeColorState.Pressed = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MaximizeButton.Image = (global::System.Drawing.Image)resources.GetObject("resource.Image1");
			_visualControlBox.MaximizeButton.Location = new global::System.Drawing.Point(24, 0);
			_visualControlBox.MaximizeButton.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			_visualControlBox.MaximizeButton.Name = "";
			_visualControlBox.MaximizeButton.OffsetLocation = new global::System.Drawing.Point(1, 1);
			_visualControlBox.MaximizeButton.Size = new global::System.Drawing.Size(24, 25);
			_visualControlBox.MaximizeButton.TabIndex = 2;
			_visualControlBox.MaximizeButton.Text = "1";
			textStyle2.Disabled = global::System.Drawing.Color.Empty;
			textStyle2.Enabled = global::System.Drawing.Color.Empty;
			textStyle2.Hover = global::System.Drawing.Color.Empty;
			textStyle2.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			_visualControlBox.MaximizeButton.TextStyle = textStyle2;
			_visualControlBox.MaximizeButton.Visible = false;
			_visualControlBox.MinimizeButton.BackColorState.Disabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.MinimizeButton.BackColorState.Enabled = global::System.Drawing.Color.Transparent;
			_visualControlBox.MinimizeButton.BackColorState.Hover = global::System.Drawing.Color.FromArgb(48, 48, 48);
			_visualControlBox.MinimizeButton.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(40, 40, 40);
			_visualControlBox.MinimizeButton.BoxType = global::VisualPlus.Structure.ControlBoxButton.ControlBoxType.Default;
			_visualControlBox.MinimizeButton.ForeColorState.Disabled = global::System.Drawing.Color.FromArgb(105, 105, 105);
			_visualControlBox.MinimizeButton.ForeColorState.Enabled = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MinimizeButton.ForeColorState.Hover = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MinimizeButton.ForeColorState.Pressed = global::System.Drawing.Color.FromArgb(128, 128, 128);
			_visualControlBox.MinimizeButton.Image = (global::System.Drawing.Image)resources.GetObject("resource.Image2");
			_visualControlBox.MinimizeButton.Location = new global::System.Drawing.Point(0, 0);
			_visualControlBox.MinimizeButton.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			_visualControlBox.MinimizeButton.Name = "";
			_visualControlBox.MinimizeButton.OffsetLocation = new global::System.Drawing.Point(2, 0);
			_visualControlBox.MinimizeButton.Size = new global::System.Drawing.Size(24, 25);
			_visualControlBox.MinimizeButton.TabIndex = 1;
			_visualControlBox.MinimizeButton.Text = "0";
			textStyle3.Disabled = global::System.Drawing.Color.Empty;
			textStyle3.Enabled = global::System.Drawing.Color.Empty;
			textStyle3.Hover = global::System.Drawing.Color.Empty;
			textStyle3.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			_visualControlBox.MinimizeButton.TextStyle = textStyle3;
			_visualControlBox.Size = new global::System.Drawing.Size(48, 25);
			btnStop.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(222, 87, 38);
			btnStop.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			btnStop.BackColorState.Hover = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnStop.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnStop.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnStop.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnStop.Border.HoverVisible = true;
			btnStop.Border.Rounding = 10;
			btnStop.Border.Thickness = 1;
			btnStop.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			btnStop.Border.Visible = true;
			btnStop.Cursor = global::System.Windows.Forms.Cursors.Hand;
			btnStop.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			btnStop.ForeColor = global::System.Drawing.Color.White;
			btnStop.Image = null;
			btnStop.Location = new global::System.Drawing.Point(361, 105);
			btnStop.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			btnStop.Name = "btnStop";
			btnStop.Size = new global::System.Drawing.Size(313, 38);
			btnStop.TabIndex = 22;
			btnStop.Text = "Stop";
			btnStop.TextAlignment = global::System.Drawing.StringAlignment.Center;
			btnStop.TextImageRelation = global::System.Windows.Forms.TextImageRelation.Overlay;
			btnStop.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle4.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle4.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle4.Hover = global::System.Drawing.Color.Empty;
			textStyle4.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			btnStop.TextStyle = textStyle4;
			btnStop.Click += new global::System.EventHandler(btnStop_Click);
			visualLabel1.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			visualLabel1.ForeColor = global::System.Drawing.Color.White;
			visualLabel1.Location = new global::System.Drawing.Point(15, 150);
			visualLabel1.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			visualLabel1.Name = "visualLabel1";
			visualLabel1.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			visualLabel1.Outline = false;
			visualLabel1.OutlineColor = global::System.Drawing.Color.Red;
			visualLabel1.OutlineLocation = new global::System.Drawing.Point(0, 0);
			visualLabel1.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			visualLabel1.ReflectionSpacing = 0;
			visualLabel1.ShadowColor = global::System.Drawing.Color.Black;
			visualLabel1.ShadowDirection = 315;
			visualLabel1.ShadowLocation = new global::System.Drawing.Point(0, 0);
			visualLabel1.ShadowOpacity = 100;
			visualLabel1.Size = new global::System.Drawing.Size(213, 21);
			visualLabel1.TabIndex = 19;
			visualLabel1.Text = "Capture Type";
			visualLabel1.TextAlignment = global::System.Drawing.StringAlignment.Near;
			visualLabel1.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle5.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle5.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle5.Hover = global::System.Drawing.Color.Empty;
			textStyle5.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			visualLabel1.TextStyle = textStyle5;
			cmbCapture.BackColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbCapture.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(255, 168, 0);
			cmbCapture.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			cmbCapture.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbCapture.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbCapture.Border.HoverVisible = true;
			cmbCapture.Border.Rounding = 10;
			cmbCapture.Border.Thickness = 1;
			cmbCapture.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			cmbCapture.Border.Visible = true;
			cmbCapture.ButtonColor = global::System.Drawing.Color.White;
			cmbCapture.ButtonImage = null;
			cmbCapture.ButtonStyle = global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox.ButtonStyles.Arrow;
			cmbCapture.ButtonWidth = 30;
			cmbCapture.Cursor = global::System.Windows.Forms.Cursors.Hand;
			cmbCapture.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawVariable;
			cmbCapture.DropDownHeight = 100;
			cmbCapture.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			cmbCapture.DropDownWidth = 77;
			cmbCapture.Font = new global::System.Drawing.Font("Segoe UI", 8.25f);
			cmbCapture.ForeColor = global::System.Drawing.Color.White;
			cmbCapture.FormattingEnabled = true;
			cmbCapture.ImageList = null;
			cmbCapture.ImageVisible = false;
			cmbCapture.Index = 0;
			cmbCapture.IntegralHeight = false;
			cmbCapture.ItemHeight = 24;
			cmbCapture.ItemImageVisible = true;
			cmbCapture.Items.AddRange(new object[]
			{
				"STILL W.I.P"
			});
			cmbCapture.Location = new global::System.Drawing.Point(15, 172);
			cmbCapture.MenuItemHover = global::System.Drawing.Color.FromArgb(242, 107, 58);
			cmbCapture.MenuItemNormal = global::System.Drawing.Color.FromArgb(220, 220, 220);
			cmbCapture.MenuTextColor = global::System.Drawing.Color.FromArgb(0, 0, 0);
			cmbCapture.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			cmbCapture.Name = "cmbCapture";
			cmbCapture.SeparatorColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbCapture.Size = new global::System.Drawing.Size(213, 30);
			cmbCapture.State = global::VisualPlus.Enumerators.MouseStates.Normal;
			cmbCapture.TabIndex = 17;
			cmbCapture.TextAlignment = global::System.Drawing.StringAlignment.Center;
			cmbCapture.TextDisabledColor = global::System.Drawing.Color.Empty;
			cmbCapture.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			cmbCapture.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			cmbCapture.TextRendering = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			textStyle6.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle6.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle6.Hover = global::System.Drawing.Color.Empty;
			textStyle6.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			cmbCapture.TextStyle = textStyle6;
			cmbCapture.Watermark.ActiveColor = global::System.Drawing.Color.FromArgb(128, 128, 128);
			cmbCapture.Watermark.Font = new global::System.Drawing.Font("Segoe UI", 8.25f);
			cmbCapture.Watermark.InactiveColor = global::System.Drawing.Color.FromArgb(211, 211, 211);
			cmbCapture.Watermark.Text = "Watermark text";
			cmbCapture.Watermark.Visible = false;
			btnStart.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(222, 87, 38);
			btnStart.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			btnStart.BackColorState.Hover = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnStart.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnStart.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnStart.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnStart.Border.HoverVisible = true;
			btnStart.Border.Rounding = 10;
			btnStart.Border.Thickness = 1;
			btnStart.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			btnStart.Border.Visible = true;
			btnStart.Cursor = global::System.Windows.Forms.Cursors.Hand;
			btnStart.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			btnStart.ForeColor = global::System.Drawing.Color.White;
			btnStart.Image = null;
			btnStart.Location = new global::System.Drawing.Point(15, 105);
			btnStart.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			btnStart.Name = "btnStart";
			btnStart.Size = new global::System.Drawing.Size(313, 38);
			btnStart.TabIndex = 16;
			btnStart.Text = "Start";
			btnStart.TextAlignment = global::System.Drawing.StringAlignment.Center;
			btnStart.TextImageRelation = global::System.Windows.Forms.TextImageRelation.Overlay;
			btnStart.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle7.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle7.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle7.Hover = global::System.Drawing.Color.Empty;
			textStyle7.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			btnStart.TextStyle = textStyle7;
			btnStart.Click += new global::System.EventHandler(btnStart_Click);
			btnCombo.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(222, 87, 38);
			btnCombo.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			btnCombo.BackColorState.Hover = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnCombo.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnCombo.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnCombo.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnCombo.Border.HoverVisible = true;
			btnCombo.Border.Rounding = 10;
			btnCombo.Border.Thickness = 1;
			btnCombo.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			btnCombo.Border.Visible = true;
			btnCombo.Cursor = global::System.Windows.Forms.Cursors.Hand;
			btnCombo.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			btnCombo.ForeColor = global::System.Drawing.Color.White;
			btnCombo.Image = null;
			btnCombo.Location = new global::System.Drawing.Point(15, 56);
			btnCombo.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			btnCombo.Name = "btnCombo";
			btnCombo.Size = new global::System.Drawing.Size(313, 38);
			btnCombo.TabIndex = 15;
			btnCombo.Text = "Combo List";
			btnCombo.TextAlignment = global::System.Drawing.StringAlignment.Center;
			btnCombo.TextImageRelation = global::System.Windows.Forms.TextImageRelation.Overlay;
			btnCombo.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle8.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle8.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle8.Hover = global::System.Drawing.Color.Empty;
			textStyle8.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			btnCombo.TextStyle = textStyle8;
			btnCombo.Click += new global::System.EventHandler(btnCombo_Click);
			lblErrors.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			lblErrors.ForeColor = global::System.Drawing.Color.FromArgb(255, 168, 0);
			lblErrors.Location = new global::System.Drawing.Point(443, 220);
			lblErrors.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			lblErrors.Name = "lblErrors";
			lblErrors.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			lblErrors.Outline = false;
			lblErrors.OutlineColor = global::System.Drawing.Color.Red;
			lblErrors.OutlineLocation = new global::System.Drawing.Point(0, 0);
			lblErrors.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			lblErrors.ReflectionSpacing = 0;
			lblErrors.ShadowColor = global::System.Drawing.Color.Black;
			lblErrors.ShadowDirection = 315;
			lblErrors.ShadowLocation = new global::System.Drawing.Point(0, 0);
			lblErrors.ShadowOpacity = 100;
			lblErrors.Size = new global::System.Drawing.Size(231, 30);
			lblErrors.TabIndex = 34;
			lblErrors.Text = "0";
			lblErrors.TextAlignment = global::System.Drawing.StringAlignment.Near;
			lblErrors.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle9.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle9.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle9.Hover = global::System.Drawing.Color.Empty;
			textStyle9.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			lblErrors.TextStyle = textStyle9;
			lblInvalid.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			lblInvalid.ForeColor = global::System.Drawing.Color.FromArgb(192, 0, 0);
			lblInvalid.Location = new global::System.Drawing.Point(443, 186);
			lblInvalid.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			lblInvalid.Name = "lblInvalid";
			lblInvalid.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			lblInvalid.Outline = false;
			lblInvalid.OutlineColor = global::System.Drawing.Color.Red;
			lblInvalid.OutlineLocation = new global::System.Drawing.Point(0, 0);
			lblInvalid.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			lblInvalid.ReflectionSpacing = 0;
			lblInvalid.ShadowColor = global::System.Drawing.Color.Black;
			lblInvalid.ShadowDirection = 315;
			lblInvalid.ShadowLocation = new global::System.Drawing.Point(0, 0);
			lblInvalid.ShadowOpacity = 100;
			lblInvalid.Size = new global::System.Drawing.Size(231, 30);
			lblInvalid.TabIndex = 33;
			lblInvalid.Text = "0";
			lblInvalid.TextAlignment = global::System.Drawing.StringAlignment.Near;
			lblInvalid.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle10.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle10.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle10.Hover = global::System.Drawing.Color.Empty;
			textStyle10.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			lblInvalid.TextStyle = textStyle10;
			lblValid.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			lblValid.ForeColor = global::System.Drawing.Color.FromArgb(0, 192, 0);
			lblValid.Location = new global::System.Drawing.Point(443, 151);
			lblValid.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			lblValid.Name = "lblValid";
			lblValid.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			lblValid.Outline = false;
			lblValid.OutlineColor = global::System.Drawing.Color.Red;
			lblValid.OutlineLocation = new global::System.Drawing.Point(0, 0);
			lblValid.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			lblValid.ReflectionSpacing = 0;
			lblValid.ShadowColor = global::System.Drawing.Color.Black;
			lblValid.ShadowDirection = 315;
			lblValid.ShadowLocation = new global::System.Drawing.Point(0, 0);
			lblValid.ShadowOpacity = 100;
			lblValid.Size = new global::System.Drawing.Size(231, 30);
			lblValid.TabIndex = 32;
			lblValid.Text = "0";
			lblValid.TextAlignment = global::System.Drawing.StringAlignment.Near;
			lblValid.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle11.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle11.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle11.Hover = global::System.Drawing.Color.Empty;
			textStyle11.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			lblValid.TextStyle = textStyle11;
			visualLabel5.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			visualLabel5.ForeColor = global::System.Drawing.Color.White;
			visualLabel5.Location = new global::System.Drawing.Point(361, 220);
			visualLabel5.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			visualLabel5.Name = "visualLabel5";
			visualLabel5.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			visualLabel5.Outline = false;
			visualLabel5.OutlineColor = global::System.Drawing.Color.Red;
			visualLabel5.OutlineLocation = new global::System.Drawing.Point(0, 0);
			visualLabel5.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			visualLabel5.ReflectionSpacing = 0;
			visualLabel5.ShadowColor = global::System.Drawing.Color.Black;
			visualLabel5.ShadowDirection = 315;
			visualLabel5.ShadowLocation = new global::System.Drawing.Point(0, 0);
			visualLabel5.ShadowOpacity = 100;
			visualLabel5.Size = new global::System.Drawing.Size(72, 30);
			visualLabel5.TabIndex = 31;
			visualLabel5.Text = " Errors:";
			visualLabel5.TextAlignment = global::System.Drawing.StringAlignment.Near;
			visualLabel5.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle12.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle12.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle12.Hover = global::System.Drawing.Color.Empty;
			textStyle12.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			visualLabel5.TextStyle = textStyle12;
			visualLabel4.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			visualLabel4.ForeColor = global::System.Drawing.Color.White;
			visualLabel4.Location = new global::System.Drawing.Point(361, 186);
			visualLabel4.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			visualLabel4.Name = "visualLabel4";
			visualLabel4.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			visualLabel4.Outline = false;
			visualLabel4.OutlineColor = global::System.Drawing.Color.Red;
			visualLabel4.OutlineLocation = new global::System.Drawing.Point(0, 0);
			visualLabel4.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			visualLabel4.ReflectionSpacing = 0;
			visualLabel4.ShadowColor = global::System.Drawing.Color.Black;
			visualLabel4.ShadowDirection = 315;
			visualLabel4.ShadowLocation = new global::System.Drawing.Point(0, 0);
			visualLabel4.ShadowOpacity = 100;
			visualLabel4.Size = new global::System.Drawing.Size(72, 30);
			visualLabel4.TabIndex = 30;
			visualLabel4.Text = " Invalid:";
			visualLabel4.TextAlignment = global::System.Drawing.StringAlignment.Near;
			visualLabel4.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle13.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle13.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle13.Hover = global::System.Drawing.Color.Empty;
			textStyle13.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			visualLabel4.TextStyle = textStyle13;
			visualLabel3.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			visualLabel3.ForeColor = global::System.Drawing.Color.White;
			visualLabel3.Location = new global::System.Drawing.Point(361, 151);
			visualLabel3.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			visualLabel3.Name = "visualLabel3";
			visualLabel3.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			visualLabel3.Outline = false;
			visualLabel3.OutlineColor = global::System.Drawing.Color.Red;
			visualLabel3.OutlineLocation = new global::System.Drawing.Point(0, 0);
			visualLabel3.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			visualLabel3.ReflectionSpacing = 0;
			visualLabel3.ShadowColor = global::System.Drawing.Color.Black;
			visualLabel3.ShadowDirection = 315;
			visualLabel3.ShadowLocation = new global::System.Drawing.Point(0, 0);
			visualLabel3.ShadowOpacity = 100;
			visualLabel3.Size = new global::System.Drawing.Size(72, 30);
			visualLabel3.TabIndex = 29;
			visualLabel3.Text = " Valid:";
			visualLabel3.TextAlignment = global::System.Drawing.StringAlignment.Near;
			visualLabel3.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle14.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle14.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle14.Hover = global::System.Drawing.Color.Empty;
			textStyle14.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			visualLabel3.TextStyle = textStyle14;
			visualLabel2.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			visualLabel2.ForeColor = global::System.Drawing.Color.White;
			visualLabel2.Location = new global::System.Drawing.Point(15, 219);
			visualLabel2.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			visualLabel2.Name = "visualLabel2";
			visualLabel2.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			visualLabel2.Outline = false;
			visualLabel2.OutlineColor = global::System.Drawing.Color.Red;
			visualLabel2.OutlineLocation = new global::System.Drawing.Point(0, 0);
			visualLabel2.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			visualLabel2.ReflectionSpacing = 0;
			visualLabel2.ShadowColor = global::System.Drawing.Color.Black;
			visualLabel2.ShadowDirection = 315;
			visualLabel2.ShadowLocation = new global::System.Drawing.Point(0, 0);
			visualLabel2.ShadowOpacity = 100;
			visualLabel2.Size = new global::System.Drawing.Size(213, 21);
			visualLabel2.TabIndex = 36;
			visualLabel2.Text = "Proxy Type";
			visualLabel2.TextAlignment = global::System.Drawing.StringAlignment.Near;
			visualLabel2.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle15.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle15.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle15.Hover = global::System.Drawing.Color.Empty;
			textStyle15.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			visualLabel2.TextStyle = textStyle15;
			cmbProxyType.BackColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbProxyType.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(255, 168, 0);
			cmbProxyType.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			cmbProxyType.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbProxyType.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbProxyType.Border.HoverVisible = true;
			cmbProxyType.Border.Rounding = 10;
			cmbProxyType.Border.Thickness = 1;
			cmbProxyType.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			cmbProxyType.Border.Visible = true;
			cmbProxyType.ButtonColor = global::System.Drawing.Color.White;
			cmbProxyType.ButtonImage = null;
			cmbProxyType.ButtonStyle = global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox.ButtonStyles.Arrow;
			cmbProxyType.ButtonWidth = 30;
			cmbProxyType.Cursor = global::System.Windows.Forms.Cursors.Hand;
			cmbProxyType.DrawMode = global::System.Windows.Forms.DrawMode.OwnerDrawVariable;
			cmbProxyType.DropDownHeight = 100;
			cmbProxyType.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			cmbProxyType.DropDownWidth = 69;
			cmbProxyType.Font = new global::System.Drawing.Font("Segoe UI", 8.25f);
			cmbProxyType.ForeColor = global::System.Drawing.Color.White;
			cmbProxyType.FormattingEnabled = true;
			cmbProxyType.ImageList = null;
			cmbProxyType.ImageVisible = false;
			cmbProxyType.Index = 0;
			cmbProxyType.IntegralHeight = false;
			cmbProxyType.ItemHeight = 24;
			cmbProxyType.ItemImageVisible = true;
			cmbProxyType.Items.AddRange(new object[]
			{
				"HTTP/S",
				"SOCKS 4",
				"SOCKS 5",
				"Proxyless"
			});
			cmbProxyType.Location = new global::System.Drawing.Point(15, 241);
			cmbProxyType.MenuItemHover = global::System.Drawing.Color.FromArgb(242, 107, 58);
			cmbProxyType.MenuItemNormal = global::System.Drawing.Color.FromArgb(220, 220, 220);
			cmbProxyType.MenuTextColor = global::System.Drawing.Color.FromArgb(0, 0, 0);
			cmbProxyType.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			cmbProxyType.Name = "cmbProxyType";
			cmbProxyType.SeparatorColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			cmbProxyType.Size = new global::System.Drawing.Size(213, 30);
			cmbProxyType.State = global::VisualPlus.Enumerators.MouseStates.Normal;
			cmbProxyType.TabIndex = 35;
			cmbProxyType.TextAlignment = global::System.Drawing.StringAlignment.Center;
			cmbProxyType.TextDisabledColor = global::System.Drawing.Color.Empty;
			cmbProxyType.TextImageRelation = global::System.Windows.Forms.TextImageRelation.ImageBeforeText;
			cmbProxyType.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			cmbProxyType.TextRendering = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			textStyle16.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle16.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle16.Hover = global::System.Drawing.Color.Empty;
			textStyle16.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			cmbProxyType.TextStyle = textStyle16;
			cmbProxyType.Watermark.ActiveColor = global::System.Drawing.Color.FromArgb(128, 128, 128);
			cmbProxyType.Watermark.Font = new global::System.Drawing.Font("Segoe UI", 8.25f);
			cmbProxyType.Watermark.InactiveColor = global::System.Drawing.Color.FromArgb(211, 211, 211);
			cmbProxyType.Watermark.Text = "Watermark text";
			cmbProxyType.Watermark.Visible = false;
			btnProxy.BackColorState.Disabled = global::System.Drawing.Color.FromArgb(222, 87, 38);
			btnProxy.BackColorState.Enabled = global::System.Drawing.Color.FromArgb(242, 107, 58);
			btnProxy.BackColorState.Hover = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnProxy.BackColorState.Pressed = global::System.Drawing.Color.FromArgb(239, 78, 20);
			btnProxy.Border.Color = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnProxy.Border.HoverColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			btnProxy.Border.HoverVisible = true;
			btnProxy.Border.Rounding = 10;
			btnProxy.Border.Thickness = 1;
			btnProxy.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			btnProxy.Border.Visible = true;
			btnProxy.Cursor = global::System.Windows.Forms.Cursors.Hand;
			btnProxy.Font = new global::System.Drawing.Font("Segoe UI", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			btnProxy.ForeColor = global::System.Drawing.Color.White;
			btnProxy.Image = null;
			btnProxy.Location = new global::System.Drawing.Point(361, 56);
			btnProxy.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			btnProxy.Name = "btnProxy";
			btnProxy.Size = new global::System.Drawing.Size(313, 38);
			btnProxy.TabIndex = 37;
			btnProxy.Text = "Proxy List";
			btnProxy.TextAlignment = global::System.Drawing.StringAlignment.Center;
			btnProxy.TextImageRelation = global::System.Windows.Forms.TextImageRelation.Overlay;
			btnProxy.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle17.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle17.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle17.Hover = global::System.Drawing.Color.Empty;
			textStyle17.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			btnProxy.TextStyle = textStyle17;
			btnProxy.Click += new global::System.EventHandler(btnProxy_Click);
			lblChecked.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			lblChecked.ForeColor = global::System.Drawing.Color.White;
			lblChecked.Location = new global::System.Drawing.Point(443, 254);
			lblChecked.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			lblChecked.Name = "lblChecked";
			lblChecked.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			lblChecked.Outline = false;
			lblChecked.OutlineColor = global::System.Drawing.Color.Red;
			lblChecked.OutlineLocation = new global::System.Drawing.Point(0, 0);
			lblChecked.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			lblChecked.ReflectionSpacing = 0;
			lblChecked.ShadowColor = global::System.Drawing.Color.Black;
			lblChecked.ShadowDirection = 315;
			lblChecked.ShadowLocation = new global::System.Drawing.Point(0, 0);
			lblChecked.ShadowOpacity = 100;
			lblChecked.Size = new global::System.Drawing.Size(231, 30);
			lblChecked.TabIndex = 39;
			lblChecked.Text = "0";
			lblChecked.TextAlignment = global::System.Drawing.StringAlignment.Near;
			lblChecked.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle18.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle18.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle18.Hover = global::System.Drawing.Color.Empty;
			textStyle18.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			lblChecked.TextStyle = textStyle18;
			lblCheckedString.Font = new global::System.Drawing.Font("Segoe UI", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			lblCheckedString.ForeColor = global::System.Drawing.Color.White;
			lblCheckedString.Location = new global::System.Drawing.Point(365, 254);
			lblCheckedString.MouseState = global::VisualPlus.Enumerators.MouseStates.Normal;
			lblCheckedString.Name = "lblCheckedString";
			lblCheckedString.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			lblCheckedString.Outline = false;
			lblCheckedString.OutlineColor = global::System.Drawing.Color.Red;
			lblCheckedString.OutlineLocation = new global::System.Drawing.Point(0, 0);
			lblCheckedString.ReflectionColor = global::System.Drawing.Color.FromArgb(120, 0, 0, 0);
			lblCheckedString.ReflectionSpacing = 0;
			lblCheckedString.ShadowColor = global::System.Drawing.Color.Black;
			lblCheckedString.ShadowDirection = 315;
			lblCheckedString.ShadowLocation = new global::System.Drawing.Point(0, 0);
			lblCheckedString.ShadowOpacity = 100;
			lblCheckedString.Size = new global::System.Drawing.Size(72, 30);
			lblCheckedString.TabIndex = 38;
			lblCheckedString.Text = "Checked:";
			lblCheckedString.TextAlignment = global::System.Drawing.StringAlignment.Near;
			lblCheckedString.TextLineAlignment = global::System.Drawing.StringAlignment.Center;
			textStyle19.Disabled = global::System.Drawing.Color.FromArgb(131, 129, 129);
			textStyle19.Enabled = global::System.Drawing.Color.FromArgb(0, 0, 0);
			textStyle19.Hover = global::System.Drawing.Color.Empty;
			textStyle19.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.ClearTypeGridFit;
			lblCheckedString.TextStyle = textStyle19;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			BackColor = global::System.Drawing.Color.FromArgb(48, 48, 48);
			base.Background = global::System.Drawing.Color.FromArgb(48, 48, 48);
			base.Border.Color = global::System.Drawing.Color.FromArgb(40, 40, 40);
			base.Border.HoverColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			base.Border.HoverVisible = true;
			base.Border.Rounding = 6;
			base.Border.Thickness = 3;
			base.Border.Type = global::VisualPlus.Enumerators.ShapeType.Rectangle;
			base.Border.Visible = true;
			base.ClientSize = new global::System.Drawing.Size(690, 289);
			base.Controls.Add(lblChecked);
			base.Controls.Add(lblCheckedString);
			base.Controls.Add(btnProxy);
			base.Controls.Add(visualLabel2);
			base.Controls.Add(cmbProxyType);
			base.Controls.Add(lblErrors);
			base.Controls.Add(lblInvalid);
			base.Controls.Add(lblValid);
			base.Controls.Add(visualLabel5);
			base.Controls.Add(visualLabel4);
			base.Controls.Add(visualLabel3);
			base.Controls.Add(btnStop);
			base.Controls.Add(visualLabel1);
			base.Controls.Add(cmbCapture);
			base.Controls.Add(btnStart);
			base.Controls.Add(btnCombo);
			base.DropShadow = false;
			ForeColor = global::System.Drawing.Color.White;
			border.Color = global::System.Drawing.Color.FromArgb(180, 180, 180);
			border.HoverColor = global::System.Drawing.Color.FromArgb(120, 183, 230);
			border.HoverVisible = false;
			border.Rounding = 6;
			border.Thickness = 1;
			border.Type = global::VisualPlus.Enumerators.ShapeType.Rounded;
			border.Visible = false;
			base.Image.Border = border;
			base.Image.Image = (global::System.Drawing.Bitmap)resources.GetObject("resource.Image3");
			base.Image.Point = new global::System.Drawing.Point(5, 7);
			base.Image.Size = new global::System.Drawing.Size(16, 16);
			base.Image.Visible = false;
			MaximumSize = new global::System.Drawing.Size(690, 289);
			base.MinimizeBox = true;
			MinimumSize = new global::System.Drawing.Size(690, 289);
			base.Name = "frmMain";
			base.ShowIcon = false;
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			Text = "SkinRoyale | Created by KeCa, Itami & Zed.";
			base.WindowBarColor = global::System.Drawing.Color.FromArgb(40, 40, 40);
			base.FormClosing += new global::System.Windows.Forms.FormClosingEventHandler(frmMain_FormClosing);
			base.Controls.SetChildIndex(btnCombo, 0);
			base.Controls.SetChildIndex(btnStart, 0);
			base.Controls.SetChildIndex(cmbCapture, 0);
			base.Controls.SetChildIndex(visualLabel1, 0);
			base.Controls.SetChildIndex(btnStop, 0);
			base.Controls.SetChildIndex(visualLabel3, 0);
			base.Controls.SetChildIndex(visualLabel4, 0);
			base.Controls.SetChildIndex(visualLabel5, 0);
			base.Controls.SetChildIndex(lblValid, 0);
			base.Controls.SetChildIndex(lblInvalid, 0);
			base.Controls.SetChildIndex(lblErrors, 0);
			base.Controls.SetChildIndex(_visualControlBox, 0);
			base.Controls.SetChildIndex(cmbProxyType, 0);
			base.Controls.SetChildIndex(visualLabel2, 0);
			base.Controls.SetChildIndex(btnProxy, 0);
			base.Controls.SetChildIndex(lblCheckedString, 0);
			base.Controls.SetChildIndex(lblChecked, 0);
			base.ResumeLayout(false);
		}

		private global::System.ComponentModel.IContainer components = null;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton btnStop;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel visualLabel1;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox cmbCapture;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton btnStart;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton btnCombo;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel lblErrors;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel lblInvalid;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel lblValid;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel visualLabel5;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel visualLabel4;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel visualLabel3;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel visualLabel2;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualComboBox cmbProxyType;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualButton btnProxy;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel lblChecked;
		private global::VisualPlus.Toolkit.Controls.Interactivity.VisualLabel lblCheckedString;
	}
}
